/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package negozioelettronica.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDialog;

import negozioelettronica.prodotti.ProdottoAstratto;
import negozioelettronica.prodotti.ProdottoInterface;
import negozioelettronica.user.User;
import negozioelettronica.utils.Carrello;
import negozioelettronica.visitors.ProdottiInfoVisitor;

/**
 *
 * @author Bardeli Edmond
 */
public class FatturaDialog extends ListenedDialog
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form FatturaDialog
     */
    public FatturaDialog(java.awt.Frame parent,Carrello carrello)
    {
        super(parent, true);
        initComponents();
        setupComponents(carrello);
    }
    
    private void setupComponents(Carrello carrello)
    {
        updateDetagliCarello(carrello);
        updateTotali(carrello); 
        
        btn_ok.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                MessageDialog messageDialog=new MessageDialog(null, true,"Grazie per aver aquistato!");
                messageDialog.setLocationRelativeTo(FatturaDialog.this);
                messageDialog.addDialogListener(new DialogListenInteface() {
                    @Override
                    public void onDialogFinish(JDialog source) {
                        FatturaDialog.this.dispose();
                        FatturaDialog.this.fireAllDialogListener();
                    }
                });
                messageDialog.setVisible(true);
                
            }
        });
        aggiornaUtente(carrello);
        
    }
    
    /**
     * aggirna i detagli del prodotto selezionato dal catalogo
     * @param prodotto 
     */
    private void updateDetagliCarello(Carrello carrello)
    {
        ProdottiInfoVisitor prodottiInfoVisitor = new ProdottiInfoVisitor(false);
        for(ProdottoInterface prodotto:carrello)
        {
            prodotto.accept(prodottiInfoVisitor);
        }
        txt_prodotto_aquistati.setText(prodottiInfoVisitor.getInfoProdotti());
        txt_prodotto_aquistati.setCaretPosition(0);
    }
    
    /**
     * aggiorna il totale senza sconto e il totale scontato
     * @param carrello 
     */
    private void updateTotali(Carrello carrello)
    {
        lbl_totale.setText(" " + ProdottoAstratto.PREZZO_FORMAT.format(carrello.getPrezzo()));
        lbl_totale_scontato.setText(" " + ProdottoAstratto.PREZZO_FORMAT.format(carrello.getPrezzoScontato()));
    }
    
    
    /**
     * aggiorna le informazioni dell'utente contenuto nell carello
     */
    private void aggiornaUtente(Carrello carrello)
    {
        User user=carrello.getUser();
        
        if(user==null)
        {
            lbl_tessera.setText("-");
            lbl_utente.setText("-");
        }else
        {
            lbl_tessera.setText(user.getTessera().getInfo());
            lbl_utente.setText(user.getInfoUtente());
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lbl_totale = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_totale_scontato = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_prodotto_aquistati = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_utente = new javax.swing.JLabel();
        lbl_tessera = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Prodotti aquistati:");

        btn_ok.setText("OK");

        jLabel3.setText("Totale:");

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(238, 238, 238));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Negozio Elettronica Bardeli Edmond\n Viale Unoduetre 4\nP.I. 12345678901");
        jTextArea2.setBorder(null);
        jScrollPane2.setViewportView(jTextArea2);

        lbl_totale.setText("-");

        jLabel5.setText("Totale scontato");

        lbl_totale_scontato.setText("-");

        jLabel1.setText("Fattura");

        txt_prodotto_aquistati.setEditable(false);
        txt_prodotto_aquistati.setBackground(new java.awt.Color(238, 238, 238));
        txt_prodotto_aquistati.setColumns(20);
        txt_prodotto_aquistati.setRows(5);
        txt_prodotto_aquistati.setBorder(null);
        jScrollPane1.setViewportView(txt_prodotto_aquistati);

        jLabel4.setText("Utente");

        jLabel6.setText("Tessera");

        lbl_utente.setText("-");

        lbl_tessera.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_totale_scontato, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 534, Short.MAX_VALUE)
                                        .addComponent(btn_ok))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(74, 74, 74)
                                                .addComponent(lbl_totale, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel6))
                                                .addGap(68, 68, 68)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbl_tessera)
                                                    .addComponent(lbl_utente))))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbl_totale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_totale_scontato)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lbl_utente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbl_tessera))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ok)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lbl_tessera;
    private javax.swing.JLabel lbl_totale;
    private javax.swing.JLabel lbl_totale_scontato;
    private javax.swing.JLabel lbl_utente;
    private javax.swing.JTextArea txt_prodotto_aquistati;
    // End of variables declaration//GEN-END:variables
}
