/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package negozioelettronica.gui;

import negozioelettronica.gui.cellrenderers.TesseraCellRenderer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import negozioelettronica.user.User;
import negozioelettronica.user.card.TesseraGold;
import negozioelettronica.user.card.TesseraGuest;
import negozioelettronica.user.card.TesseraInterface;
import negozioelettronica.user.card.TesseraStandard;

/**
 * 
 * @author Bardeli Edmond
 */
public class LoginFrame extends javax.swing.JFrame
{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private DefaultComboBoxModel<TesseraInterface> tessereModel=new DefaultComboBoxModel<>();
    

    
    public LoginFrame()
    {
        initComponents();
        setupComponents();
    }
    
    /**
     * setta i componenti del frame
     */
    private void setupComponents()
    {
        initTesseraModel();
        comboBox_tipo_member.setModel(tessereModel);
        comboBox_tipo_member.setRenderer(new TesseraCellRenderer());
        
        btn_ok.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                LoginFrame.this.setVisible(false);
            }
        });
    }
    
    /**
     * crea l'utente basandosi sul campo username e la tessera scelta nel combobox
     * @return l'utente selezionato
     */
    public User createUser()
    {
        return new User((String) comboBoxTitolo.getSelectedItem(),txt_username.getText(), (TesseraInterface) comboBox_tipo_member.getSelectedItem());
    }
    
    /**
     * aggiunge alla lista le tessere Guest, Standard e Gold
     */
    private void initTesseraModel()
    {
        tessereModel.addElement(new TesseraGuest());
        tessereModel.addElement(new TesseraStandard());
        tessereModel.addElement(new TesseraGold());
    }
    
    

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  private void initComponents()
    {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBox_tipo_member = new javax.swing.JComboBox<>();
        txt_username = new javax.swing.JTextField();
        btn_ok = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboBoxTitolo = new javax.swing.JComboBox<>();

        jLabel3.setText("jLabel3");

        setUndecorated(true);
        setResizable(false);

        jLabel1.setText("Username:");

        jLabel2.setText("Tipo");

        btn_ok.setText("OK");

        jLabel4.setText("Titolo");

        comboBoxTitolo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sig", "Sig.a" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_ok))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(comboBox_tipo_member, 0, 212, Short.MAX_VALUE)
                    .addComponent(comboBoxTitolo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboBoxTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBox_tipo_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ok))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JComboBox<String> comboBoxTitolo;
    private javax.swing.JComboBox<TesseraInterface> comboBox_tipo_member;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
